# Generated by Django 5.0.4 on 2024-04-06 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MyUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                ("dob", models.DateField()),
                (
                    "likes_chocolate",
                    models.CharField(
                        choices=[("L", "Likes Chocolate"), ("D", "Dislikes Chocolate")],
                        default="L",
                        max_length=1,
                    ),
                ),
                ("age_first_taste_chocolate", models.IntegerField(null=True)),
            ],
        ),
    ]
